In [13]:
from __future__ import division
import pyfits
import numpy as np
from matplotlib import pyplot as plt
import pyregion

def rebin(a, shape):
    sh = shape[0],a.shape[0]//shape[0],shape[1],a.shape[1]//shape[1]
    return a.reshape(sh).mean(-1).mean(1)
# def reflag(a):
#     c=[]
#     for i in range(0,a.shape[0],4):
#         for j in range(0,a.shape[1],4):
#             b=np.bincount(np.asarray(a[i:i+4,j:j+4]).astype(int).flatten())
#             if len(b)>1: 
#                 c.append(np.argmax(b[1:])+1)
#             else:
#                 c.append(np.argmax(b))
#     return np.asarray(c).reshape((a.shape[0]//4,a.shape[1]//4))
# def fill(x):
#     new=np.zeros((1400,1400))
#     for i in range(1400):
#         for j in range(1400):
#             if (x[i])[j]==0:
#                 new[i,j]=1
#             else:
#                 new[i,j]=(x[i])[j]
#     return new



final_5600=np.zeros((10,5600,5600))
    
strarr=['2530,2371','2732,3611','2761,3405','2794,2048']  #lower_bcg,upper_bcg,one below lcg,below_arc
region=np.asarray([[2345,2699,2211,2571],[2512,2957,3402,3842],[2677,2845,3339,3484],[2753,2835,2009,2085]])
flag=[2,3,1,4]

########### galfit assignment ############

for i in range(4):
    f=pyfits.open('/home/lkit/Softwares/galfit3.0.5/work/'+strarr[i]+'/ds9.fits')
    im=f[0].data
    f.close()
    final_5600[flag[i]-1,region[i,2]:region[i,3]+1,region[i,0]:region[i,1]+1]=im[:,:]/(10**5)

f=pyfits.open('/home/lkit/Data/Jan_data/30mas_v0.5_f160w.fits')
im=np.asarray(f[0].data)
f.close()    

######## normal regions #########

fnum=[1,5,6,7,8,9,10]

for num in fnum:
    region='/home/lkit/wslap/data/A370/fiducial/fiducial_mass_region'+str(num)
    r=pyregion.open(region)
    mask=r.get_mask(shape=(5600,5600))
    for i in range(5600):
        for j in range(5600):
            if (mask[i])[j]:
                final_5600[num-1,i,j]=im[i,j]/(10**5)

                
# f=open('/home/lkit/wslap/data/A370/fiducial/fiducial_mass_region'+str(num))
# region=[map(int,line.split()) for line in f]
# f.close()
# for i in region:
#     y1=i[2]; y2=i[3]; x1=i[0]; x2=i[1]
#     final_5600[num-1,y1:y2,x1:x2]=im[y1:y2,x1:x2]/(10**5)
                
# region_name3 = '/home/lkit/wslap/data/A370/fiducial/fiducial_mass_region3.reg'
# region_name4 = '/home/lkit/wslap/data/A370/fiducial/fiducial_mass_region4.reg'
# r3=pyregion.open(region_name3)
# r4=pyregion.open(region_name4)
# mask3= r3.get_mask(shape=(5600,5600))
# mask4= r4.get_mask(shape=(5600,5600))

# for i in range(5600):
#     for j in range(5600):
#         if (mask3[i])[j]:
#             final_5600[2,i,j]=im[i,j]/(10**5)
#         if (mask4[i])[j]:
#             final_5600[3,i,j]=im[i,j]/(10**5)

final_1400=[0]*10
for i in range(10):
    final_1400[i]=rebin(final_5600[i],(1400,1400))
final_1400=np.asarray(final_1400)

f=open('/home/lkit/wslap/data/A370/fiducial/mass_map_A370.dat','w')
for k in range(10):
    for i in range(1400):
        for j in range(1400):
            f.write('\t\t%d\t\t%d\t\t%.15f\t\t%d\n' %(i+1,j+1,final_1400[k,j,i],k+1))
f.close()

# plt.imshow(final_1400[0])
# plt.show()

print 'done'


TypeError: Invalid dimensions for image data

In [22]:
for i in range(10):
    plt.imshow(final_1400[i])
    plt.show()



In [293]:
import pyregion
region_name3 = '/home/lkit/wslap/data/A370/fiducial/fiducial_mass_region3.reg'
region_name4 = '/home/lkit/wslap/data/A370/fiducial/fiducial_mass_region4.reg'
r3=pyregion.open(region_name3)
r4=pyregion.open(region_name4)
mask3= r3.get_mask(shape=(5600,5600))
mask4= r4.get_mask(shape=(5600,5600))

test=np.ones((5600,5600))
final=np.zeros((5600,5600))
for i in range(5600):
    for j in range(5600):
        if (mask3[i])[j]:
            final[i,j]=final[i,j]+test[i,j]
        if (mask4[i])[j]:
            final[i,j]=final[i,j]+test[i,j]

plt.imshow(final)
plt.show()


In [4]:
import numpy as np
a=np.asarray([[1,2],[3,4]])
b=np.zeros((3,3))
print b
b[0:3,0:3]=a[:,:]
print b

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


ValueError: could not broadcast input array from shape (2,2) into shape (3,3)