In [65]:
import numpy as np
import matplotlib.pyplot as plt
import random


E = 0.1
M = 5
def ln(x):
    return np.log(x)/np.log(np.e)

def CDF_inv(x, e, m):  
    A = 1/(1 + np.log(m/e))
    if x == 1:
        return m
    elif 0 <= x <= A:
        return e * x / A
    elif A < x < 1:
        return e * np.exp((x / A) - 1)


n = 1000
random_num = [random.random() for e in range(n)]
random_sample = [CDF_inv(x, E, M) for x in random_num]
stretch = [10.0, 10.0]

def get_coordinates_elliptical(distribution=CDF_inv, params=[E, M],stretch=stretch):
    R = distribution(random.random(), *params)
    theta = random.random() * 2 * np.pi
    return (R * np.cos(theta) * stretch[0], R * np.sin(theta) * stretch[1])

zeta_list = [get_coordinates_elliptical() for e in range(n)]
x1, y1= zip(*zeta_list)

x1 = np.asarray(x1)
y1 = np.asarray(y1)



zeta_list = np.column_stack((x1,y1))
zeta_list = np.asarray(zeta_list)



ok


In [62]:
E = 0.1
M = 5
def ln(x):
    return np.log(x)/np.log(np.e)

def CDF_inv(x, e, m):   # x=random, e,m=fixed
    A = 1/(1 + np.log(m/e))
    if x == 1:
        return m
    elif 0 <= x <= A:
        return e * x / A
    elif A < x < 1:
        return e * np.exp((x / A) - 1)
    
result=[]
for i in np.linspace(0,1,100):
    result.append(CDF_inv(i,0.1,5))

plt.plot(result)
plt.show()

In [66]:
x=[1,2,3,4]
y=[2,3,4,5]
print np.column_stack((x,y))

[[1 2]
 [2 3]
 [3 4]
 [4 5]]


In [82]:
xx=[]
x = np.linspace(-50,50,10)
y = np.linspace(-50,50,10)
xx.append(x)
x1,y1 = np.meshgrid(x,y)
print x1
print y1
# print xx
# print xx[0]
# print x
# print x[0]

[[-50.         -38.88888889 -27.77777778 -16.66666667  -5.55555556
    5.55555556  16.66666667  27.77777778  38.88888889  50.        ]
 [-50.         -38.88888889 -27.77777778 -16.66666667  -5.55555556
    5.55555556  16.66666667  27.77777778  38.88888889  50.        ]
 [-50.         -38.88888889 -27.77777778 -16.66666667  -5.55555556
    5.55555556  16.66666667  27.77777778  38.88888889  50.        ]
 [-50.         -38.88888889 -27.77777778 -16.66666667  -5.55555556
    5.55555556  16.66666667  27.77777778  38.88888889  50.        ]
 [-50.         -38.88888889 -27.77777778 -16.66666667  -5.55555556
    5.55555556  16.66666667  27.77777778  38.88888889  50.        ]
 [-50.         -38.88888889 -27.77777778 -16.66666667  -5.55555556
    5.55555556  16.66666667  27.77777778  38.88888889  50.        ]
 [-50.         -38.88888889 -27.77777778 -16.66666667  -5.55555556
    5.55555556  16.66666667  27.77777778  38.88888889  50.        ]
 [-50.         -38.88888889 -27.77777778 -16.66666667  

In [96]:
from __future__ import division

x1=np.asarray([[1,2,3],
               [4,5,6]])
x2=np.asarray([[2,6,7],
               [8,2,5]])

def square(x_array,y_array):
    return x_array**2+y_array**2

print square(x1,x2)
print square(x1,x2)*2

[[ 5 40 58]
 [80 29 61]]
[[ 10  80 116]
 [160  58 122]]


In [117]:
god=[]
for i in range(3):
    god2=[]
    for j in range(3):
        god2.append(j)
    god.append(god2)
god=np.asarray(god)
print god
print god[1,2]

[[0 1 2]
 [0 1 2]
 [0 1 2]]
2


In [135]:
god=np.asarray([[[0,0] for j in range(3)] for i in range(3)])

god[2,0,1]=6
print god

[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 6]
  [0 0]
  [0 0]]]
