In [48]:
import pyfits
import numpy as np
fname='/home/lkit/Data/Jan_data/hlsp_frontier_hst_wfc3-30mas_abell370_f140w_v0.5-20160121_drz.fits'
f=pyfits.open(fname)

n=[ range(10) for i in range(10)]
hdu=pyfits.PrimaryHDU(n)  #create PrimeryHDU object to encapsulate data
hdu.writeto('/home/lkit/tmp/new.fits',clobber=True)

print n

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]


/home/lkit/.local/lib/python2.7/site-packages/pyfits/file.py:372: UserWarning: Overwriting existing file '/home/lkit/tmp/new.fits'.
  warnings.warn("Overwriting existing file %r." % self.name)


In [49]:
from __future__ import division

a=np.arange(24).reshape((4,6))
print a
print a.reshape((2,a.shape[0]//2,3,-1)).mean(axis=3).mean(1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[  3.5   5.5   7.5]
 [ 15.5  17.5  19.5]]
